# the settings from here should not be edited or overwritten
routes:
  admin_plugins:
    pattern:  /manager/
    defaults: { _controller: plugins\riCore\AdminController::indexAction }
  admin_plugins_info:
    pattern:  /info/
    defaults: { _controller: plugins\riCore\AdminController::pluginsInfoAction }
  admin_plugins_install:
    pattern:  /install/
    defaults: { _controller: plugins\riCore\AdminController::pluginsInstallAction }
  admin_plugins_uninstall:
    pattern:  /uninstall/
    defaults: { _controller: plugins\riCore\AdminController::pluginsUninstallAction }
  admin_plugins_activate:
    pattern:  /activate/
    defaults: { _controller: plugins\riCore\AdminController::pluginsActivateAction }
  admin_plugins_deactivate:
    pattern:  /deactivate/
    defaults: { _controller: plugins\riCore\AdminController::pluginsDeactivateAction }
  admin_plugins_reset:
    pattern:  /reset_settings/
    defaults: { _controller: plugins\riCore\AdminController::pluginsResetAction }
  admin_plugins_load_theme_settings:
    pattern:  /load_theme_settings/
    defaults: { _controller: plugins\riCore\AdminController::loadThemeSettingsAction }

global:    
  backend:
    menu:
      extras:
        - {text: Plugins Manager, link: ri.php/ricore/manager/}